[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"
authors = ["Prateek Singh Rathore <prateek.singh.rathore@gmail.com>"]
description = "Simple hello world program"

[[bin]]
name = "hello_world"
path = "main.rs"
